import { useMemo, useState } from "react";

type Prompt={q:string;cat:"Playful"|"Thoughtful"|"Team";time:number};
const prompts:Prompt[]=[
{q:"What’s a tiny hill you’re willing to die on?",cat:"Playful",time:45},{q:"What’s something you’ve changed your mind about recently?",cat:"Thoughtful",time:60},{q:"Which fictional world would you move to tomorrow?",cat:"Playful",time:45},{q:"What instantly makes a team feel welcoming?",cat:"Team",time:60},{q:"What skill would you download into your brain?",cat:"Playful",time:45},{q:"What’s a compliment you still remember?",cat:"Thoughtful",time:60},{q:"What’s your most controversial food opinion?",cat:"Playful",time:30},{q:"What makes you feel most energized at work?",cat:"Team",time:60},{q:"What would your personal warning label say?",cat:"Playful",time:45},{q:"What’s a small ritual that makes your day better?",cat:"Thoughtful",time:60},{q:"What should every great meeting include?",cat:"Team",time:45},{q:"If your week had a movie title, what would it be?",cat:"Playful",time:45}];
const cats=[{n:"Playful",d:"Low stakes, high smiles",c:"coral",art:"✦"},{n:"Thoughtful",d:"Go a little deeper",c:"lilac",art:"◒"},{n:"Team",d:"Build better chemistry",c:"mint",art:"◎"}];
const Arrow=()=> <svg viewBox="0 0 24 24"><path d="M5 12h14m-6-6 6 6-6 6"/></svg>;
const Logo=()=> <div className="brand"><b>✦</b>warmly</div>;
export default function App(){
 const [chosen,setChosen]=useState(["Playful","Thoughtful","Team"]); const [playing,setPlaying]=useState(false); const [at,setAt]=useState(0); const [liked,setLiked]=useState<number[]>([]); const [copied,setCopied]=useState(false);
 const deck=useMemo(()=>prompts.filter(p=>chosen.includes(p.cat)),[chosen]); const card=deck[at%deck.length]||prompts[0];
 const toggle=(n:string)=>setChosen(v=>v.includes(n)?v.length===1?v:v.filter(x=>x!==n):[...v,n]);
 const next=()=>{setAt(v=>(v+1)%deck.length);setCopied(false)};
 const copy=async()=>{await navigator.clipboard.writeText(card.q);setCopied(true);setTimeout(()=>setCopied(false),1400)};
 if(playing)return <main className="session"><nav><button onClick={()=>setPlaying(false)}><Logo/></button><span className="live">● Session in progress</span><button className="round" onClick={()=>setPlaying(false)}>×</button></nav><section className="play"><header><div><small>QUESTION {at+1} OF {deck.length}</small><i><b style={{width:`${(at+1)/deck.length*100}%`}}/></i></div><span className={card.cat.toLowerCase()}>{card.cat}</span></header><article><i>✦</i><small>ASK THE ROOM</small><h1>{card.q}</h1><p>◷ About {card.time} seconds each</p><i>✦</i></article><div className="actions"><button className={liked.includes(at)?"round liked":"round"} onClick={()=>setLiked(v=>v.includes(at)?v.filter(x=>x!==at):[...v,at])}>♡</button><button className="primary" onClick={next}>Next question <Arrow/></button><button className="round" onClick={copy}>{copied?"✓":"□"}</button></div><button className="surprise" onClick={()=>setAt(Math.floor(Math.random()*deck.length))}>↻ Surprise me</button></section></main>;
 return <main><nav><Logo/><div className="links"><a href="#how">How it works</a><a href="#decks">Decks</a></div><button className="primary small" onClick={()=>setPlaying(true)}>Start a session <Arrow/></button></nav><section className="hero"><div className="hello">HELLO!<i/></div><div className="heroCopy"><span className="kicker">✦ BETTER CONVERSATIONS START HERE</span><h1>Skip the small talk.<br/><em>Start something real.</em></h1><p>Thoughtful prompts for teams, friends, and humans who want to connect—without the awkwardness.</p><button className="primary big" onClick={()=>setPlaying(true)}>Break the ice <Arrow/></button><div className="proof"><div><b>AM</b><b>RK</b><b>JL</b><b>+2k</b></div><p><strong>Loved by 2,000+ teams</strong><br/>Making Mondays less Monday-ish.</p></div></div></section><section className="builder" id="decks"><header><div><small>MAKE IT YOURS</small><h2>What’s the vibe?</h2></div><p>Pick one or mix a few. We’ll build the perfect deck for your room.</p></header><div className="grid">{cats.map(x=><button key={x.n} className={`cat ${x.c} ${chosen.includes(x.n)?"selected":""}`} onClick={()=>toggle(x.n)}><b className="check">{chosen.includes(x.n)?"✓":"+"}</b><i>{x.art}</i><strong>{x.n}</strong><span>{x.d}</span><small>{prompts.filter(p=>p.cat===x.n).length} PROMPTS</small></button>)}</div><div className="summary"><p><b>▣</b><span><strong>Your custom deck</strong><br/>{deck.length} hand-picked prompts</span></p><button className="primary" onClick={()=>{setAt(0);setPlaying(true)}}>Start this deck <Arrow/></button></div></section><section className="how" id="how"><small>NO PREP. NO CRINGE.</small><h2>Ready in three, two, fun.</h2><div>{[["01","♙","Gather your people","In a room or on a call. Anywhere works."],["02","ϟ","Pick your vibe","Choose a deck that fits the moment."],["03","♡","Get talking","One prompt. Countless good conversations."]].map(s=><article key={s[0]}><small>{s[0]}</small><b>{s[1]}</b><h3>{s[2]}</h3><p>{s[3]}</p></article>)}</div></section><footer><Logo/><p>Built for better hellos.</p><button onClick={()=>setPlaying(true)}>Try a prompt →</button></footer></main>
}
